# PPO mountian car 
param_grid:
  hidden_size:
    - 32
    - 64
    - 128
  lr_policy:
    - 0.0001
    - 0.001
    - 0.01
  lr_critic:
    - 0.0001
    - 0.001
    - 0.01
  gamma:
    - 0.9
    - 0.95
    - 0.99
  clip_val:
    - 0.1
    - 0.2
    - 0.3
