num_experiments: 500
results_dir: "/Users/--/Documents/--/Research/ns_gym_project/ns_gym_experiments/results/ddpg_mountaincar_eval_default"
experiment_name: "ddpg_default_baseline"
logs_dir: "/Users/--/Documents/--/Research/ns_gym_project/ns_gym_experiments/logs/ddpg_mountaincar_eval_default"

model_path: "/Users/--/Documents/--/Research/ns_gym_project/ns_gym_experiments/models/ddpg_mountaincar/ddpg_mountiancar_default"

num_exp: 500

num_workers: 5

env_name: "MountainCarContinuous-v0"

device: "cpu"

tunable_params: "power"

change_notification: True

max_steps: 999